"""Unit tests for report module."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

SRC = Path(__file__).resolve().parent.parent / "src"
sys.path.insert(0, str(SRC))

from abaqus_mcp_pro.report import (
    SimulationReport,
    format_report_markdown,
    format_report_compact,
    build_report,
    save_report,
)
from abaqus_mcp_pro.capsule import CapsuleEntry
from abaqus_mcp_pro.contracts import ContractReport, ContractResult
from abaqus_mcp_pro.solver_diagnosis import DiagnosisReport, DiagnosticEvent
from abaqus_mcp_pro.odb_lens import KPILensReport, KPIResult
from abaqus_mcp_pro.silent_failures import SilentFailureReport, SilentFailureFinding


class TestSimulationReport:
    def test_defaults(self):
        r = SimulationReport()
        assert r.title == "Abaqus Simulation Report"
        assert r.generated_at != ""
        assert r.capsule is None
        assert r.kpi_lens is None
        assert r.contracts is None
        assert r.diagnosis is None
        assert r.silent_failures is None
        assert r.screenshots == []
        assert r.extra_sections == {}

    def test_custom_title(self):
        r = SimulationReport(title="My Custom Report")
        assert r.title == "My Custom Report"

    def test_with_capsule(self):
        c = CapsuleEntry(capsule_id="test")
        r = SimulationReport(capsule=c)
        assert r.capsule is c

    def test_with_all_sections(self):
        capsule = CapsuleEntry(capsule_id="test")
        kpi = KPILensReport(odb_path="/tmp/test.odb")
        contracts = ContractReport()
        diagnosis = DiagnosisReport(job_name="test", workdir="/tmp")
        sf = SilentFailureReport(model_name="test")
        r = SimulationReport(
            capsule=capsule, kpi_lens=kpi, contracts=contracts, diagnosis=diagnosis,
            silent_failures=sf,
            screenshots=["/tmp/shot.png"],
            extra_sections={"Notes": "Some custom notes."},
        )
        assert r.capsule is capsule
        assert r.kpi_lens is kpi
        assert r.contracts is contracts
        assert r.diagnosis is diagnosis
        assert r.silent_failures is sf
        assert len(r.screenshots) == 1
        assert "Notes" in r.extra_sections


class TestFormatReportMarkdownEmpty:
    def test_empty_report(self):
        r = SimulationReport()
        md = format_report_markdown(r)
        assert "Abaqus Simulation Report" in md
        assert "Generated:" in md
        assert "Report generated by abaqus-mcp-pro" in md

    def test_empty_report_no_sections(self):
        r = SimulationReport()
        md = format_report_markdown(r)
        assert "Model & Job Summary" not in md
        assert "KPI Lens Results" not in md
        assert "Physics Contracts" not in md
        assert "Solver Diagnosis" not in md
        assert "Screenshots" not in md


class TestFormatReportMarkdownCapsule:
    def test_basic_capsule(self):
        c = CapsuleEntry(
            capsule_id="run_001", abaqus_version="2024",
            job_name="Job-1", job_status="COMPLETED",
            workdir="/tmp", notes="baseline",
        )
        r = SimulationReport(capsule=c)
        md = format_report_markdown(r)
        assert "Model & Job Summary" in md
        assert "2024" in md
        assert "Job-1" in md
        assert "COMPLETED" in md
        assert "baseline" in md

    def test_capsule_with_model_info(self):
        c = CapsuleEntry(
            capsule_id="test",
            model_info={
                "Model-1": {
                    "parts": ["Part-1", "Part-2"],
                    "materials": ["Steel"],
                    "steps": ["Step-1"],
                }
            },
        )
        r = SimulationReport(capsule=c)
        md = format_report_markdown(r)
        assert "Part-1" in md
        assert "Part-2" in md
        assert "Steel" in md
        assert "Step-1" in md

    def test_capsule_with_files(self):
        c = CapsuleEntry(
            capsule_id="test",
            files=[
                {"name": "job.odb", "size": 2_500_000},
                {"name": "job.msg", "size": 500},
            ],
        )
        r = SimulationReport(capsule=c)
        md = format_report_markdown(r)
        assert "job.odb" in md
        assert "2.5 MB" in md
        assert "job.msg" in md
        assert "500 B" in md

    def test_capsule_with_kb_file(self):
        c = CapsuleEntry(
            capsule_id="test",
            files=[{"name": "job.inp", "size": 5_000}],
        )
        r = SimulationReport(capsule=c)
        md = format_report_markdown(r)
        assert "5.0 KB" in md


class TestFormatReportMarkdownKPILens:
    def test_with_results(self):
        kpi = KPILensReport(odb_path="/tmp/test.odb")
        kpi.add_result(KPIResult(
            query_id="max_stress", value=345.6,
            metadata={"field": "S", "aggregation": "max", "step": "Step-1", "frame": 5},
        ))
        kpi.add_result(KPIResult(
            query_id="max_disp", value=0.012,
            metadata={"field": "U", "aggregation": "max", "step": "Step-1", "frame": "last"},
        ))
        r = SimulationReport(kpi_lens=kpi)
        md = format_report_markdown(r)
        assert "KPI Lens Results" in md
        assert "max_stress" in md
        assert "345.6" in md
        assert "max_disp" in md
        assert "0.012" in md
        assert "max" in md

    def test_with_errors(self):
        kpi = KPILensReport(odb_path="/tmp/test.odb")
        kpi.add_result(KPIResult(query_id="bad", error="Field not found"))
        r = SimulationReport(kpi_lens=kpi)
        md = format_report_markdown(r)
        assert "ERROR: Field not found" in md

    def test_no_results(self):
        kpi = KPILensReport(odb_path="/tmp/test.odb")
        r = SimulationReport(kpi_lens=kpi)
        md = format_report_markdown(r)
        assert "KPI Lens Results" in md
        assert "test.odb" in md


class TestFormatReportMarkdownContracts:
    def test_all_pass(self):
        ct = ContractReport()
        ct.add_result(ContractResult(
            contract_id="c1", kpi_name="stress", passed=True,
            actual=345.0, expected_display="[0, 500]", message="OK",
        ))
        r = SimulationReport(contracts=ct)
        md = format_report_markdown(r)
        assert "ALL CONTRACTS PASSED" in md
        assert "PASS" in md

    def test_some_fail(self):
        ct = ContractReport()
        ct.add_result(ContractResult(
            contract_id="c1", kpi_name="stress", passed=False,
            actual=600.0, expected_display="[0, 500]", message="Outside range",
        ))
        r = SimulationReport(contracts=ct)
        md = format_report_markdown(r)
        assert "CONTRACT(S) FAILED" in md
        assert "FAIL" in md

    def test_empty_contracts(self):
        ct = ContractReport()
        r = SimulationReport(contracts=ct)
        md = format_report_markdown(r)
        assert "Physics Contracts" in md


class TestFormatReportMarkdownDiagnosis:
    def test_with_events(self):
        diag = DiagnosisReport(
            job_name="Job-1", workdir="/tmp",
            files_scanned=["job.msg", "job.sta"],
        )
        diag.add_event(DiagnosticEvent(
            category="license", severity="error", pattern_id="license_unavailable",
            file="job.msg", line=5, raw_line="License not available",
            suggestion="Check license server.",
        ))
        diag.add_event(DiagnosticEvent(
            category="convergence", severity="warning", pattern_id="too_many_attempts",
            file="job.msg", line=10, raw_line="Too many attempts",
            suggestion="Reduce initial increment size.",
        ))
        r = SimulationReport(diagnosis=diag)
        md = format_report_markdown(r)
        assert "Solver Diagnosis" in md
        assert "license_unavailable" in md
        assert "too_many_attempts" in md
        assert "Check license server" in md
        assert "job.msg" in md
        assert "job.sta" in md

    def test_empty_events(self):
        diag = DiagnosisReport(job_name="Job-1", workdir="/tmp")
        r = SimulationReport(diagnosis=diag)
        md = format_report_markdown(r)
        assert "Solver Diagnosis" in md
        assert "Job-1" in md


class TestFormatReportMarkdownScreenshots:
    def test_with_screenshots(self):
        r = SimulationReport(screenshots=["/tmp/shot1.png", "/tmp/shot2.png"])
        md = format_report_markdown(r)
        assert "Screenshots" in md
        assert "shot1.png" in md
        assert "shot2.png" in md

    def test_no_screenshots(self):
        r = SimulationReport()
        md = format_report_markdown(r)
        assert "Screenshots" not in md


class TestFormatReportMarkdownSilentFailures:
    def test_with_silent_failures(self):
        sf = SilentFailureReport(model_name="TestModel")
        sf.add_finding(SilentFailureFinding(
            category="mesh_integrity", severity="error", check_id="mesh_zero_elements",
            passed=False, detail="Part has 1 cell but 0 elements",
            suggestion="Check elemShape",
        ))
        sf.add_finding(SilentFailureFinding(
            category="mesh_integrity", severity="info", check_id="mesh_ok",
            passed=True, detail="Part has 1 cell, 32 elements",
        ))
        r = SimulationReport(silent_failures=sf)
        md = format_report_markdown(r)
        assert "Silent Failure Detection" in md
        assert "mesh_zero_elements" in md
        assert "mesh_ok" in md
        assert "FAIL" in md
        assert "PASS" in md

    def test_no_silent_failures(self):
        r = SimulationReport()
        md = format_report_markdown(r)
        assert "Silent Failure Detection" not in md


class TestFormatReportMarkdownCustom:
    def test_custom_section(self):
        r = SimulationReport(
            extra_sections={"Notes": "Custom note content.", "Appendix": "More data."},
        )
        md = format_report_markdown(r)
        assert "Notes" in md
        assert "Custom note content" in md
        assert "Appendix" in md
        assert "More data" in md


class TestFormatReportCompact:
    def test_empty(self):
        r = SimulationReport()
        compact = format_report_compact(r)
        assert "Report:" in compact

    def test_with_capsule(self):
        c = CapsuleEntry(capsule_id="test", job_name="Job-1", job_status="COMPLETED")
        r = SimulationReport(capsule=c)
        compact = format_report_compact(r)
        assert "test" in compact
        assert "Job-1" in compact
        assert "COMPLETED" in compact

    def test_with_all(self):
        capsule = CapsuleEntry(capsule_id="test", job_name="Job-1", job_status="COMPLETED")
        kpi = KPILensReport(odb_path="/tmp/test.odb")
        kpi.add_result(KPIResult(query_id="q1", value=100.0))
        ct = ContractReport()
        ct.add_result(ContractResult(contract_id="c1", kpi_name="s", passed=True, message="OK"))
        diag = DiagnosisReport(job_name="test", workdir="/tmp")
        diag.add_event(DiagnosticEvent(
            category="general", severity="info", pattern_id="done",
            file="x.log", line=1, raw_line="done", suggestion="ok",
        ))
        sf = SilentFailureReport(model_name="test")
        sf.add_finding(SilentFailureFinding(
            category="mesh_integrity", severity="error", check_id="mesh_zero",
            passed=False, detail="No elements",
        ))
        r = SimulationReport(
            capsule=capsule, kpi_lens=kpi, contracts=ct, diagnosis=diag,
            silent_failures=sf,
            screenshots=["/tmp/shot.png"],
        )
        compact = format_report_compact(r)
        assert "Capsule: test" in compact
        assert "KPI Lens: 1 OK" in compact
        assert "Contracts: 1 passed" in compact
        assert "Diagnosis: 0 errors" in compact
        assert "Silent Failures: 1 failed" in compact
        assert "Screenshots: 1" in compact


class TestBuildReport:
    def test_build_empty(self):
        r = build_report(title="Test")
        assert r.title == "Test"
        assert r.capsule is None

    def test_build_with_capsule(self):
        c = CapsuleEntry(capsule_id="test")
        r = build_report(capsule=c)
        assert r.capsule is c

    def test_build_with_all(self):
        c = CapsuleEntry(capsule_id="test")
        kpi = KPILensReport(odb_path="/tmp/test.odb")
        ct = ContractReport()
        diag = DiagnosisReport(job_name="test", workdir="/tmp")
        sf = SilentFailureReport(model_name="test")
        r = build_report(
            title="Full Report", capsule=c, kpi_lens=kpi,
            contracts=ct, diagnosis=diag,
            silent_failures=sf,
            screenshots=["/tmp/shot.png"],
            extra_sections={"Notes": "hello"},
        )
        assert r.title == "Full Report"
        assert r.capsule is c
        assert r.kpi_lens is kpi
        assert r.contracts is ct
        assert r.diagnosis is diag
        assert r.silent_failures is sf
        assert len(r.screenshots) == 1
        assert r.extra_sections["Notes"] == "hello"


class TestSaveReport:
    def test_save_to_file(self, tmp_path):
        c = CapsuleEntry(capsule_id="test", job_name="Job-1", job_status="COMPLETED")
        r = SimulationReport(capsule=c)
        path = str(tmp_path / "report.md")
        saved = save_report(r, path)
        assert saved == str(Path(path).resolve())
        assert Path(path).exists()
        content = Path(path).read_text(encoding="utf-8")
        assert "Abaqus Simulation Report" in content
        assert "Job-1" in content

    def test_save_creates_directory(self, tmp_path):
        r = SimulationReport()
        path = str(tmp_path / "subdir" / "report.md")
        save_report(r, path)
        assert Path(path).exists()

    def test_save_full_report(self, tmp_path):
        capsule = CapsuleEntry(capsule_id="test", job_name="Job-1", job_status="COMPLETED")
        kpi = KPILensReport(odb_path="/tmp/test.odb")
        kpi.add_result(KPIResult(query_id="max_stress", value=345.6))
        ct = ContractReport()
        ct.add_result(ContractResult(contract_id="c1", kpi_name="stress", passed=True, actual=345.0, expected_display="[0, 500]", message="OK"))
        diag = DiagnosisReport(job_name="test", workdir="/tmp")
        r = SimulationReport(
            capsule=capsule, kpi_lens=kpi, contracts=ct, diagnosis=diag,
            screenshots=["/tmp/shot.png"],
        )
        path = str(tmp_path / "full_report.md")
        save_report(r, path)
        content = Path(path).read_text(encoding="utf-8")
        assert "Model & Job Summary" in content
        assert "KPI Lens Results" in content
        assert "Physics Contracts" in content
        assert "Solver Diagnosis" in content
        assert "Screenshots" in content
        assert "Report generated by abaqus-mcp-pro" in content
