import socket, json, uuid, os, time

def send_message(sock, payload):
    data = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    sock.sendall(data + b"\n")

def read_message(sock):
    chunks = []
    while True:
        chunk = sock.recv(4096)
        if not chunk:
            break
        nl = chunk.find(b"\n")
        if nl >= 0:
            chunks.append(chunk[:nl])
            break
        chunks.append(chunk)
    return json.loads(b"".join(chunks).decode("utf-8"))

def execute(code, timeout=60):
    sock = socket.create_connection(("127.0.0.1", 48152), timeout=timeout)
    sock.settimeout(timeout)
    payload = {"id": str(uuid.uuid4()), "method": "execute", "params": {"code": code, "timeout": timeout}}
    send_message(sock, payload)
    resp = read_message(sock)
    sock.close()
    return resp

work_dir = r"R:\100_Private\WQG\codex\ABAQUS MCP\abaqus-mcp-pro\examples\output\classic_tensile"
os.makedirs(work_dir, exist_ok=True)

# Step 1: Import and build model
code1 = r'''
import os
os.chdir(__WORK_DIR__)

from abaqus import mdb
from abaqusConstants import *
import mesh
import regionToolset

MODEL_NAME = "Classic_Tensile_Bar"
JOB_NAME = "classic_tensile_bar"

if MODEL_NAME in mdb.models:
    del mdb.models[MODEL_NAME]

model = mdb.Model(name=MODEL_NAME)

length = 100.0
width = 10.0
height = 10.0
imposed_u1 = 1.0

sketch = model.ConstrainedSketch(name="bar_profile", sheetSize=160.0)
sketch.rectangle(point1=(0.0, -height / 2.0), point2=(length, height / 2.0))

part = model.Part(name="Tensile_Bar", dimensionality=THREE_D, type=DEFORMABLE_BODY)
part.BaseSolidExtrude(sketch=sketch, depth=width)
del model.sketches["bar_profile"]

material = model.Material(name="Steel_Elastic")
material.Elastic(table=((210000.0, 0.30),))

section = model.HomogeneousSolidSection(name="Steel_Section", material="Steel_Elastic")
part.SectionAssignment(
    region=regionToolset.Region(cells=part.cells[:]),
    sectionName="Steel_Section",
)

part.seedPart(size=5.0, deviationFactor=0.1, minSizeFactor=0.1)
part.setMeshControls(regions=part.cells[:], elemShape=HEX, technique=STRUCTURED)
elem_type = mesh.ElemType(elemCode=C3D8R, elemLibrary=STANDARD)
part.setElementType(regions=(part.cells[:],), elemTypes=(elem_type,))
part.generateMesh()

assembly = model.rootAssembly
assembly.DatumCsysByDefault(CARTESIAN)
inst = assembly.Instance(name="Tensile_Bar-1", part=part, dependent=ON)

eps = 1.0e-3
left_faces = inst.faces.getByBoundingBox(
    xMin=-eps, xMax=eps,
    yMin=-height, yMax=height,
    zMin=-eps, zMax=width + eps,
)
right_nodes = inst.nodes.getByBoundingBox(
    xMin=length - eps, xMax=length + eps,
    yMin=-height, yMax=height,
    zMin=-eps, zMax=width + eps,
)

assembly.Set(name="FIXED_END", faces=left_faces)
assembly.Set(name="PULLED_END_NODES", nodes=right_nodes)

model.StaticStep(name="Tension", previous="Initial", nlgeom=OFF)

model.EncastreBC(
    name="Fixed_Left_End",
    createStepName="Initial",
    region=assembly.sets["FIXED_END"],
)
model.DisplacementBC(
    name="Right_End_U1_1mm",
    createStepName="Tension",
    region=assembly.sets["PULLED_END_NODES"],
    u1=imposed_u1,
    u2=UNSET,
    u3=UNSET,
    ur1=UNSET,
    ur2=UNSET,
    ur3=UNSET,
)

mdb.Job(
    name=JOB_NAME,
    model=MODEL_NAME,
    description="Classic 3D tensile bar benchmark generated by Codex.",
    type=ANALYSIS,
    memory=90,
    memoryUnits=PERCENTAGE,
    numCpus=2,
    numDomains=2,
)

mdb.saveAs(pathName=os.path.join(os.getcwd(), JOB_NAME + ".cae"))

result = {"model_built": True, "job_name": JOB_NAME, "model_name": MODEL_NAME, "cwd": os.getcwd()}
'''.replace("__WORK_DIR__", json.dumps(work_dir))

print("=== Step 1: Building model ===")
resp = execute(code1, timeout=120)
print(json.dumps(resp, indent=2, ensure_ascii=False))
